os: osx
language: objective-c

install:
  - "brew update"
  - "brew install swig"
  - "brew install python"
  - hash -r python

script:
  - "./build.sh picosat-960"
  - python setup.py install
  - python demo.py
